# Generated by Django 3.1.7 on 2021-06-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180322_1544'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('api', '0009_auto_20210628_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='authentication.User'),
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
